using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SharpShader.CSharp.Frontend;

namespace SharpShader.CSharp.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class SharpSLGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                static (productionContext, compilation) => Execute(productionContext, compilation));
        }

        private static void Execute(SourceProductionContext context, Compilation compilation)
        {
            CSharpShaderTranslation translation = new CSharpShaderTranslator().Translate(
                compilation,
                context.CancellationToken);
            for (int index = 0; index < translation.Diagnostics.Count; ++index)
            {
                CSharpShaderDiagnostic diagnostic = translation.Diagnostics[index];
                context.ReportDiagnostic(Diagnostic.Create(
                    SharpSLGeneratorDescriptors.Get(diagnostic.Id, diagnostic.Severity),
                    ResolveLocation(compilation, diagnostic),
                    diagnostic.Message));
            }

            if (translation.HasErrors || translation.Entries.Count == 0)
            {
                return;
            }

            context.AddSource(
                "SharpSL.Translated.g.cs",
                SourceText.From(EmitSource(compilation.AssemblyName, translation), Encoding.UTF8));
        }

        private static string EmitSource(string? assemblyName, CSharpShaderTranslation translation)
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("internal static class SharpSLGenerated");
            builder.AppendLine("{");
            builder.Append("    public const string AssemblyName = @\"");
            builder.Append((assemblyName ?? "ShaderAssembly").Replace("\"", "\"\""));
            builder.AppendLine("\";");
            builder.Append("    public const string Hlsl = @\"");
            builder.Append(translation.Hlsl.Replace("\"", "\"\""));
            builder.AppendLine("\";");
            builder.Append("    public const int EntryCount = ");
            builder.Append(translation.Entries.Count);
            builder.AppendLine(";");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static Location ResolveLocation(Compilation compilation, CSharpShaderDiagnostic diagnostic)
        {
            if (string.IsNullOrWhiteSpace(diagnostic.Path) || diagnostic.Line <= 0)
            {
                return Location.None;
            }

            foreach (SyntaxTree tree in compilation.SyntaxTrees)
            {
                if (!string.Equals(tree.FilePath, diagnostic.Path, StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(tree.FilePath, diagnostic.Path, StringComparison.Ordinal))
                {
                    continue;
                }

                Microsoft.CodeAnalysis.Text.SourceText text = tree.GetText();
                if (diagnostic.Line > text.Lines.Count)
                {
                    return Location.Create(tree, default);
                }

                Microsoft.CodeAnalysis.Text.TextLine line = text.Lines[diagnostic.Line - 1];
                int start = line.Start + Math.Max(diagnostic.Column - 1, 0);
                if (start > line.End)
                {
                    start = line.Start;
                }

                return Location.Create(
                    tree,
                    Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(start, Math.Min(start + 1, line.End)));
            }

            return Location.None;
        }
    }
}
