<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>x64;ARM64</Platforms>
    <AssemblyName>SharpShader.CSharp.ShaderLib</AssemblyName>
    <RootNamespace>SharpShader.CSharp.ShaderLib</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>


  <PropertyGroup><Version>$(StackPackageVersion)</Version><RepositoryUrl>https://github.com/haolange/SharpShader</RepositoryUrl></PropertyGroup>
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../../../README.md" Pack="true" PackagePath="README.md" Visible="false" />
    <None Include="../../../../LICENSE" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
</Project>
