<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />
  <PropertyGroup>
    <UseHostCompilerIfAvailable>false</UseHostCompilerIfAvailable>
    <BaseIntermediateOutputPath>$(ProjectDir)../../../Intermediate/Graphics/SharpShader/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(ProjectDir)../../../Intermediate/Graphics/SharpShader/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**/._*.cs" />
    <None Remove="**/._*" />
    <Content Remove="**/._*" />
  </ItemGroup>
</Project>
