<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x64;ARM64</Platforms>
    <AssemblyName>SharpShader.CSharp</AssemblyName>
    <RootNamespace>SharpShader.CSharp</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Infinity.Rendering.Tests" />
    <ProjectReference Include="../SharpShader.csproj" Condition="'$(StackReferenceMode)' == 'Source'" />
    <ProjectReference Include="Frontend/SharpShader.CSharp.Frontend.csproj" Condition="'$(StackReferenceMode)' == 'Source'" />
    <ProjectReference Include="ShaderLib/SharpShader.CSharp.ShaderLib.csproj" Condition="'$(StackReferenceMode)' == 'Source'" />
    <ProjectReference Include="$(SharpMathRoot)/src/SharpMath/SharpMath.csproj"  Condition="'$(StackReferenceMode)' == 'Source'" StackProduct="SharpMath" StackRoot="$(SharpMathRoot)" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Frontend\**\*.cs" />
    <Compile Remove="ShaderLib\**\*.cs" />
  </ItemGroup>


  <PropertyGroup><Version>$(StackPackageVersion)</Version><RepositoryUrl>https://github.com/haolange/SharpShader</RepositoryUrl></PropertyGroup>
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../../README.md" Pack="true" PackagePath="README.md" Visible="false" />
    <None Include="../../../LICENSE" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpShader" Version="$(StackPackageVersion)" Condition="'$(StackReferenceMode)' == 'Package'" />
    <PackageReference Include="SharpShader.CSharp.Frontend" Version="$(StackPackageVersion)" Condition="'$(StackReferenceMode)' == 'Package'" />
    <PackageReference Include="SharpShader.CSharp.ShaderLib" Version="$(StackPackageVersion)" Condition="'$(StackReferenceMode)' == 'Package'" />
    <PackageReference Include="SharpMath" Version="$(StackPackageVersion)" Condition="'$(StackReferenceMode)' == 'Package'" />
  </ItemGroup>
</Project>
